// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCULvOTznkIUfZboGvNdBkHTnRNjXeLqec',
    appId: '1:931043724889:web:5ac0e8edea28a48a0e2b48',
    messagingSenderId: '931043724889',
    projectId: 'to-do-aplikasi',
    authDomain: 'to-do-aplikasi.firebaseapp.com',
    storageBucket: 'to-do-aplikasi.firebasestorage.app',
    measurementId: 'G-QRK9YN8EBK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAD6z52UkrGgOIXGnbNP5nTLLlbYH_P5U',
    appId: '1:931043724889:android:10166efa44fe53040e2b48',
    messagingSenderId: '931043724889',
    projectId: 'to-do-aplikasi',
    storageBucket: 'to-do-aplikasi.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCULvOTznkIUfZboGvNdBkHTnRNjXeLqec',
    appId: '1:931043724889:web:c92f4fe4e4f509690e2b48',
    messagingSenderId: '931043724889',
    projectId: 'to-do-aplikasi',
    authDomain: 'to-do-aplikasi.firebaseapp.com',
    storageBucket: 'to-do-aplikasi.firebasestorage.app',
    measurementId: 'G-991F45XF3Z',
  );
}
